### ISSUE TITLE
Integrate with NF Systems Manager

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/SystemHeat#11]
Few things:

- All new/modified part modules need to report their power parameters to the Systems Manager
- The Systems Manager needs to disable its thermal section when SH is installed.

**Comment by Gabe-Venberg** [comment]
> The Systems Manager needs to disable its thermal section when SH is installed.

Are you sure? just because SH is installed doesn't necessarily mean there are no parts using stock modules, unless there are dynamic patches for

* radiators
* fission generators (some mods have compatibility with NFE)
* fission engines (again, compatibility with NFE)
* drills
* converters (in pull request)
* fission engines (again, compatibility with NFE)

I *think* that's the minimum patches needed in order to guarantee that there are no stock part modules left.

As NF system manager is the only mod I know of that provides heat planning, so it would be a bit of a bummer if it stopped working on stock part modules because SH is installed.

**Comment by ChrisAdderley** [comment]
Probably right, but it will certainly cause user confusion...

**Comment by ChrisAdderley** [comment]
Current state is 'good enough'
