### ISSUE TITLE
Optimization: Enabling coolant tanks to be dropped during ascent.

### ISSUE THREAD

**Issue by KSP-Rocketeer** [post-kerbin-mining-corporation/SystemHeat#72]
System heat not robust against using coolant tanks as drop tanks. Details see here:
https://forum.kerbalspaceprogram.com/index.php?/topic/112027-111x-heat-control-more-radiators-jan-19-2020/page/30/&tab=comments#comment-4006774

**Comment by ChrisAdderley** [comment]
Thought about this and besides checking that it doesn't break loops, I think it's working as expected. Because loops have only a single temperature, if you have a loop with 40 volume and you remove 35 of it, it'll now just behave as a loop with 5 temperature. To create coolant drop tanks, you would have to use heat exchangers to send the heat to functionally separate loops that you could then 'drop' wholesale.

**Comment by ChrisAdderley** [comment]
Actions

- [ ] Verify that a coolant tank removal in flight does not cause simulation problems
- [ ] Verify that a heat exchanger that has its target loop removed in flight does not have simulation problems

**Comment by KSP-Rocketeer** [comment]
Yeah, but surely it's not intended, that the temperature gets stuck at 1300K (with ouroboros engine) when dropping the tanks, even if a great heat source (greater than cooling capacity) is still firing continously until you stop the engine once. This is the point of my report. This enables exploity builds.

And after shutting down all engines being stuck at max temp is surely not intended too, i would guess. 


My testcase: 
Dropping tanks: heat shoots up (expected due to reduced thermal capacity), but gets stuck at 1300K (not expected, since i had installed few cooling radiators) even if heat-heavy engine is still burning.
Then i stopped the engine. Still 1300K. Re-ignition: temperature now rises above 1300K (expected). Engine shut down: temperature falls (expected) but gets stuck at 1300K (not expected).

**Comment by ChrisAdderley** [comment]
Well yes, hence the 'Actions' post above....
